vusion/cloud-ui-materials

src/components/lcap-amap-nav.vue/index.vue
src/components/lcap-amap-nav.vue/package.json

扩展组件 @lcap/mobile-ui 样式冲突解决方案，已经发到 [测试环境](http://defaulttenant.lcap.ha.test.com/dashboard/app/list)

feat: 🎸 lcap-amap-nav.vue: 生产移除 @lcap/mobile-ui 样式

---

ant_design_vue_library/components/cw-auto-complete/index.vue

fix: 值更新的时候传递update事来与UFormItem同步。MField只会处理update,input,change,focus,blur事件

fix: 值更新的时候传递update事来与UFormItem同步。

---

src/components/lcap-printPage/index.vue
src/components/lcap-printPage/package.json

fix:更改lcap-printPage名为lcap-print-page

fix:更改lcap-printPage名为lcap-print-page

---

calendar_library/package-lock.json
packages/cust/cust_community_icon_image/components/cust-community-icon-image/api.yaml
packages/cust/cust_community_icon_image/components/cust-community-icon-image/docs/blocks.md
packages/cust/cust_community_icon_image/components/cust-community-icon-image/docs/examples.md
packages/cust/cust_community_icon_image/components/cust-community-icon-image/index.js
packages/cust/cust_community_icon_image/components/cust-community-icon-image/index.vue
packages/cust/cust_community_icon_image/components/cust-community-icon-image/wrap.js
packages/cust/cust_community_icon_image/index.js
packages/cust/cust_community_icon_image/manifest
packages/cust/cust_community_icon_image/package-lock.json
packages/cust/cust_community_icon_image/package.json
packages/cust/cust_community_icon_image/vusion.config.js

feat: 新增cust_community_icon_image依赖库

feat: 新增cust_community_icon_image依赖库

---

packages/cw/cw_video_library/components/cw-video-view/api.yaml
packages/cw/cw_video_library/components/cw-video-view/docs/blocks.md
packages/cw/cw_video_library/components/cw-video-view/docs/examples.md
packages/cw/cw_video_library/components/cw-video-view/index.css
packages/cw/cw_video_library/components/cw-video-view/index.js
packages/cw/cw_video_library/components/cw-video-view/index.vue
packages/cw/cw_video_library/index.js
packages/cw/cw_video_library/package-lock.json
packages/cw/cw_video_library/package.json
packages/cw/cw_video_library/vusion.config.js

1. 移动端在没有poster属性的时候可以拿到视频图像（依赖了播放和定时暂停，可能不是首帧图像）。
2. 移动端可以正确设置breakProgress。

feat: 迁移cw_video_library并修复在移动端的表现：

---

packages/cw/cw_countup/components/cx-countup/api.yaml
packages/cw/cw_countup/components/cx-countup/docs/blocks.md
packages/cw/cw_countup/components/cx-countup/docs/examples.md
packages/cw/cw_countup/components/cx-countup/index.js
packages/cw/cw_countup/components/cx-countup/index.vue
packages/cw/cw_countup/index.js
packages/cw/cw_countup/manifest
packages/cw/cw_countup/package.json
packages/cw/cw_countup/vusion.config.js

feat: countup

---

packages/cw/cw_amap/components/cw-amap-point-maker-less/api.yaml
packages/cw/cw_amap/components/cw-amap-point-maker-less/docs/examples.md
packages/cw/cw_amap/components/cw-amap-point-maker-less/index.vue
packages/cw/cw_amap/components/cw-amap-point-marker-cluster/api.yaml
packages/cw/cw_amap/components/cw-amap-point-marker-cluster/docs/examples.md
packages/cw/cw_amap/components/cw-amap-point-marker-cluster/index.vue
packages/cw/cw_amap/components/cw-amap-point-marker-label/api.yaml
packages/cw/cw_amap/components/cw-amap-point-marker-more/api.yaml
packages/cw/cw_amap/manifest
packages/cw/cw_amap/package.json
packages/cw/cw_amap/utils/createMapMarkerStore.js
packages/cw/cw_filestream_download/index.js
packages/cw/cw_filestream_download/logics/filestreamDownloadFromUrl/api.yaml
packages/cw/cw_filestream_download/logics/filestreamDownloadFromUrl/index.js
packages/cw/cw_filestream_download/logics/index.js
packages/cw/cw_filestream_download/manifest
packages/cw/cw_filestream_download/package.json
packages/cw/cw_filestream_download/vusion.config.js
packages/cw/cw_office_sdk/components/cw-ppt-preview/docs/examples.md
packages/cw/cw_office_sdk/components/cw-xlsx-preview/docs/blocks.md
packages/cw/cw_office_sdk/components/cw-xlsx-preview/docs/examples.md
packages/cw/cw_office_sdk/components/cw-xlsx-preview/index.vue
packages/cw/cw_office_sdk/manifest
packages/cw/cw_qrcode_library/components/cw-qrcode-scan-view/index.vue

Task-2795962597330432: 新增cw_filestream_download

Task-2795962597330432: 新增cw_filestream_download

---

packages/cw/cw_dragable_list/CHANGELOG.md
packages/cw/cw_dragable_list/components/cw-dragable-list/api.yaml
packages/cw/cw_dragable_list/components/cw-dragable-list/docs/blocks.md
packages/cw/cw_dragable_list/components/cw-dragable-list/docs/examples.md
packages/cw/cw_dragable_list/components/cw-dragable-list/index.js
packages/cw/cw_dragable_list/components/cw-dragable-list/index.vue
packages/cw/cw_dragable_list/index.js
packages/cw/cw_dragable_list/manifest
packages/cw/cw_dragable_list/package.json
packages/cw/cw_dragable_list/vusion.config.js
packages/cw/cw_drawing_image_view_library/components/cw-drawing-image-view/index.vue
packages/cw/cw_drawing_image_view_library/manifest

Associated Task: [#282015](https://projectmanage.netease-official.lcap.163yun.com/dashboard/TaskDetail?id=2820159012457216)
- [ebded08](https://github.com/vusion/cloud-ui-materials/commit/ebded08c2ac0bb1d75b4c8dc8d9e2b8f6586770c) Thanks [xuguanjie](https://github.com/xuguanjie) ! - 可拖拽列表
- [298b12a](https://github.com/vusion/cloud-ui-materials/commit/298b12a6c7d8709ba81039a814d58d413491cb65) Thanks [xuguanjie](https://github.com/xuguanjie) ! - 可拖拽列表
- [7df9548](https://github.com/vusion/cloud-ui-materials/commit/7df95487099d40feecaac965387b4734be90a405) Thanks [xuguanjie](https://github.com/xuguanjie) ! - 没数据的时候不更新

Task 2820159012457216 cw dragable list xuguanjie 240305

---

packages/cw/cw_drawing_image_view_library/CHANGELOG.md
packages/cw/cw_drawing_image_view_library/components/cw-drawing-image-view/index.vue
packages/cw/cw_drawing_image_view_library/manifest
packages/cw/cw_drawing_image_view_library/package.json

Associated Task: [#282014](https://projectmanage.netease-official.lcap.163yun.com/dashboard/TaskDetail?id=2820142194158336)
- [8106777](https://github.com/vusion/cloud-ui-materials/commit/8106777e4800c55c870073900532346c0d1eaad4) Thanks [xuguanjie](https://github.com/xuguanjie) ! - 修复数据为null的bug

fix: 修复数据为null的bug

---

packages/cw/cw_cryptojs_library/CHANGELOG.md
packages/cw/cw_cryptojs_library/logics/decryptByDes/api.yaml
packages/cw/cw_cryptojs_library/logics/decryptByDes/index.js
packages/cw/cw_cryptojs_library/logics/index.js
packages/cw/cw_cryptojs_library/package.json

Associated Task: [#282086](https://projectmanage.netease-official.lcap.163yun.com/dashboard/TaskDetail?id=2820863925175808)
- [7f42695](https://github.com/vusion/cloud-ui-materials/commit/7f42695c28e6f6a3d2a762f2d0af98901c2fe4fa) Thanks [ncqwer](https://github.com/ncqwer) ! - 新增des解密方法。

feat: 新增des解密方法。

---

packages/cw/cw_amap/CHANGELOG.md
packages/cw/cw_amap/components/cw-amap-poi/index.vue
packages/cw/cw_amap/components/cw-amap-point-maker-less/docs/examples.md
packages/cw/cw_amap/components/cw-amap-point-marker-3-d/api.yaml
packages/cw/cw_amap/components/cw-amap-point-marker-3-d/docs/blocks.md
packages/cw/cw_amap/components/cw-amap-point-marker-3-d/docs/examples.md
packages/cw/cw_amap/components/cw-amap-point-marker-3-d/index.js
packages/cw/cw_amap/components/cw-amap-point-marker-3-d/index.vue
packages/cw/cw_amap/components/cw-amap-point-marker-3-d/makeScatterLayerStore.js
packages/cw/cw_amap/components/cw-amap-point-marker-3-d/makeZmarkerLayer.js
packages/cw/cw_amap/index.js
packages/cw/cw_amap/manifest
packages/cw/cw_amap/mixins/infowindow.js
packages/cw/cw_amap/package.json
packages/cw/cw_amap/utils/getAMapInstance.js
packages/cw/cw_amap/vue.config.js
packages/cw/cw_amap/vusion.config.js

Associated Task: [#284010](https://projectmanage.netease-official.lcap.163yun.com/dashboard/TaskDetail?id=2840101268660480)
- [081aa0e](https://github.com/vusion/cloud-ui-materials/commit/081aa0e8246b8227d844f0e618477f4e856e64d1) Thanks [ncqwer](https://github.com/ncqwer) ! - 新增3d标记点

feat: 新增3d标记点

---

scripts/utils/collectCommitInfo.js
scripts/utils/genChangeLog.js

Fix: 
- 基于远端main分支进行匹配，避免pr分支mergemain分支后，无法获得有效的commit信息
- 更新task url

Fix updatepr update task url 240407 hanshijie

---

packages/cust/cust_community_icon_image/CHANGELOG.md
packages/cust/cust_community_icon_image/components/cust-community-icon-image/docs/examples.md
packages/cust/cust_community_icon_image/components/cust-community-icon-image/wrap.js
packages/cust/cust_community_icon_image/manifest
packages/cust/cust_community_icon_image/package.json
scripts/utils/isPackageExist.js

Associated Task: [#175](https://ddmkhcgpt.netease-official.lcap.163yun.com/dashboard/addWorkOrder?workOrderId=175)
- [3ade904](https://github.com/vusion/cloud-ui-materials/commit/3ade904adb08474363a680d217758509820c3f73) Thanks [ncqwer](https://github.com/ncqwer) ! - 支持中文地址

fix: 支持中文地址

---

packages/cw/cw_drawing_image_view_library/components/cw-drawing-image-view/api.yaml
packages/cw/cw_drawing_image_view_library/components/cw-drawing-image-view/docs/examples.md
packages/cw/cw_drawing_image_view_library/components/cw-drawing-image-view/index.vue
packages/cw/cw_drawing_image_view_library/manifest
packages/cw/cw_drawing_image_view_library/package.json

Associated Task: [#WO2024](https://ddmkhcgpt.netease-official.lcap.163yun.com/dashboard/addWorkOrder?workOrderId=WO20240329001)
- [036dddb](https://github.com/vusion/cloud-ui-materials/commit/036dddb4313781a2c34cadcaf9415cc79e53721b) Thanks [xuguanjie](https://github.com/xuguanjie) ! - 科百特画布组件ID返显bug修复

fix:科百特画布组件ID返显bug修复

---

packages/cw/cw_cryptojs_library/CHANGELOG.md
packages/cw/cw_cryptojs_library/logics/index.js
packages/cw/cw_cryptojs_library/logics/md52Hex/api.yaml
packages/cw/cw_cryptojs_library/logics/md52Hex/index.js
packages/cw/cw_cryptojs_library/manifest
packages/cw/cw_cryptojs_library/package.json

Associated Task: [#259](https://ddmkhcgpt.netease-official.lcap.163yun.com/dashboard/addWorkOrder?workOrderId=259)
- [33cfc40](https://github.com/vusion/cloud-ui-materials/commit/33cfc4047d0f8af55dccbff52de927224fbde5f9) Thanks [ncqwer](https://github.com/ncqwer) ! - 新增摘要算法md52hex

feat: 新增摘要算法md52hex

---

packages/cust/cust_community_transition/CHANGELOG.md
packages/cust/cust_community_transition/components/cust-community-transition/api.yaml
packages/cust/cust_community_transition/components/cust-community-transition/docs/blocks.md
packages/cust/cust_community_transition/components/cust-community-transition/docs/examples.md
packages/cust/cust_community_transition/components/cust-community-transition/index.js
packages/cust/cust_community_transition/components/cust-community-transition/index.vue
packages/cust/cust_community_transition/components/cust-community-transition/s-empty.vue
packages/cust/cust_community_transition/index.js
packages/cust/cust_community_transition/manifest
packages/cust/cust_community_transition/package.json
packages/cust/cust_community_transition/vusion.config.js

Associated Task: [#214](https://ddmkhcgpt.netease-official.lcap.163yun.com/dashboard/addWorkOrder?workOrderId=214)
- [2db69a4](https://github.com/vusion/cloud-ui-materials/commit/2db69a4fae4bb0490fb81b3f7987ea5ef25f5824) Thanks [ncqwer](https://github.com/ncqwer) ! - 包装transition-group

feat: 包装transition-group

---

packages/cw/cw_echarts_library/CHANGELOG.md
packages/cw/cw_echarts_library/components/cw-echart-bar-view/index.vue
packages/cw/cw_echarts_library/components/cw-echart-basic-view/index.vue
packages/cw/cw_echarts_library/components/cw-echart-line-view/index.vue
packages/cw/cw_echarts_library/components/cw-echart-pie-view/index.vue
packages/cw/cw_echarts_library/package.json

Associated Task: [#283651](https://projectmanage.netease-official.lcap.163yun.com/dashboard/TaskDetail?id=2836511638497280)
- [50e882d](https://github.com/vusion/cloud-ui-materials/commit/50e882d4f4f6efe06c30cdbf5eaac5db1aaabbec) Thanks [wangxue08](https://github.com/wangxue08) ! - 去除图表边框
- [239ac87](https://github.com/vusion/cloud-ui-materials/commit/239ac87b396b752d52ad0a9e2932c8fa902898d3) Thanks [wangxue08](https://github.com/wangxue08) ! - 昆仑数智：去除图表边框

Task 2836511638497280 cw echarts library

---

packages/cw/cw_text_power_library/CHANGELOG.md
packages/cw/cw_text_power_library/components/cw-wang-editor/api.yaml
packages/cw/cw_text_power_library/components/cw-wang-editor/docs/examples.md
packages/cw/cw_text_power_library/components/cw-wang-editor/index.vue
packages/cw/cw_text_power_library/components/cw-wang-editor/slateToDocx/blockquote.js
packages/cw/cw_text_power_library/components/cw-wang-editor/slateToDocx/code.js
packages/cw/cw_text_power_library/components/cw-wang-editor/slateToDocx/divider.js
packages/cw/cw_text_power_library/components/cw-wang-editor/slateToDocx/header.js
packages/cw/cw_text_power_library/components/cw-wang-editor/slateToDocx/image.js
packages/cw/cw_text_power_library/components/cw-wang-editor/slateToDocx/index.js
packages/cw/cw_text_power_library/components/cw-wang-editor/slateToDocx/link.js
packages/cw/cw_text_power_library/components/cw-wang-editor/slateToDocx/list.js
packages/cw/cw_text_power_library/components/cw-wang-editor/slateToDocx/paragraph.js
packages/cw/cw_text_power_library/components/cw-wang-editor/slateToDocx/table.js
packages/cw/cw_text_power_library/components/cw-wang-editor/slateToDocx/video.js
packages/cw/cw_text_power_library/manifest
packages/cw/cw_text_power_library/package-lock.json
packages/cw/cw_text_power_library/package.json

Associated Task: [#unkown](https://ddmkhcgpt.netease-official.lcap.163yun.com/dashboard/addWorkOrder?workOrderId=unkown)
- [4358d19](https://github.com/vusion/cloud-ui-materials/commit/4358d19b174ec5729ef323a4435354a19193064b) Thanks [ncqwer](https://github.com/ncqwer) ! - 新增导出docx文档和docx片段的功能

feat: 新增导出docx文档和docx片段的功能

---

packages/cw/cw_echarts_library/components/cw-echart-bar-view/index.vue
packages/cw/cw_echarts_library/components/cw-echart-basic-view/index.vue
packages/cw/cw_echarts_library/components/cw-echart-line-view/index.vue
packages/cw/cw_echarts_library/components/cw-echart-pie-view/index.vue
packages/cw/cw_echarts_library/manifest
packages/cw/cw_echarts_library/package.json

Associated Task: [#unkown](https://ddmkhcgpt.netease-official.lcap.163yun.com/dashboard/addWorkOrder?workOrderId=unkown)
- [95426aa](https://github.com/vusion/cloud-ui-materials/commit/95426aa5ec6a95275c64172cb1e3abb0294dc921) Thanks [ncqwer](https://github.com/ncqwer) ! - 修复取消边框和width和height后默认大小为0*0的问题

fix: 修复取消边框和width和height后默认大小为0*0的问题

---

packages/cust/cust_community_icon_image/components/cust-community-icon-image/image-with-mask.vue
packages/cust/cust_community_icon_image/manifest
packages/cust/cust_community_icon_image/package.json

Associated Task: [#unkown](https://ddmkhcgpt.netease-official.lcap.163yun.com/dashboard/addWorkOrder?workOrderId=unkown)
- [1ba4681](https://github.com/vusion/cloud-ui-materials/commit/1ba4681a33464be51871b8382b1bc084f004b960) Thanks [ncqwer](https://github.com/ncqwer) ! - 去除额外的console.log

fix: 去除额外的console.log

---

packages/cw/cw_office_sdk/components/cw-doc-preview/api.yaml
packages/cw/cw_office_sdk/components/cw-doc-preview/index.vue
packages/cw/cw_office_sdk/manifest
packages/cw/cw_office_sdk/package.json

Associated Task: [#unknow](https://ddmkhcgpt.netease-official.lcap.163yun.com/dashboard/addWorkOrder?workOrderId=unknown)
- [fb69099](https://github.com/vusion/cloud-ui-materials/commit/fb690993513d64c4d4c8f17e0574b5788127cc83) Thanks [ncqwer](https://github.com/ncqwer) ! - support for ignore paper's width/height

feat: support for ignore paper's width/height

---

packages/cw/cw_echarts_library/components/cw-echart-bar-view/index.vue
packages/cw/cw_echarts_library/components/cw-echart-line-view/index.vue
packages/cw/cw_echarts_library/components/cw-echart-pie-view/index.vue
packages/cw/cw_echarts_library/manifest
packages/cw/cw_echarts_library/package.json

Associated Task: [#WO2024](https://ddmkhcgpt.netease-official.lcap.163yun.com/dashboard/addWorkOrder?workOrderId=WO20240611011)
- [5163f0f9](https://github.com/vusion/cloud-ui-materials/commit/5163f0f965c148a653682028e081bf540cf2038a) Thanks [xuguanjie](https://github.com/xuguanjie) ! - 修改reload引起的堆栈问题

fix:修改reload引起的堆栈问题
